const phrases = [
    // Basic - Osnovno
    { id: 1, es: "Hola", sl: "Pozdravljeni", cat: "basic" },
    { id: 2, es: "Buenos días", sl: "Dobro jutro", cat: "basic" },
    { id: 3, es: "Buenas tardes", sl: "Dober dan", cat: "basic" },
    { id: 4, es: "Buenas noches", sl: "Dober večer", cat: "basic" },
    { id: 5, es: "Gracias", sl: "Hvala", cat: "basic" },
    { id: 6, es: "De nada", sl: "Ni za kaj", cat: "basic" },
    { id: 7, es: "Por favor", sl: "Prosim", cat: "basic" },
    { id: 8, es: "Perdón", sl: "Oprostite", cat: "basic" },
    { id: 9, es: "Lo siento", sl: "Opravičujem se", cat: "basic" },
    { id: 10, es: "Sí", sl: "Ja", cat: "basic" },
    { id: 11, es: "No", sl: "Ne", cat: "basic" },
    { id: 12, es: "¿Habla inglés?", sl: "Ali govorite angleško?", cat: "basic" },
    { id: 13, es: "No entiendo", sl: "Ne razumem", cat: "basic" },
    { id: 14, es: "¿Me puede ayudar?", sl: "Mi lahko pomagate?", cat: "basic" },
    { id: 15, es: "¿Cuánto cuesta?", sl: "Koliko stane?", cat: "basic" },
    { id: 16, es: "¿Dónde está el baño?", sl: "Kje je stranišče?", cat: "basic" },
    { id: 17, es: "¿Dónde está...?", sl: "Kje je...?", cat: "basic" },
    { id: 18, es: "¿Cómo llego a...?", sl: "Kako pridem do...?", cat: "basic" },
    { id: 19, es: "Mucho gusto", sl: "Vesel/a spoznanja", cat: "basic" },
    { id: 20, es: "Hasta luego", sl: "Se vidimo", cat: "basic" },
    
    // Airport - Letališče
    { id: 21, es: "¿Dónde está el check-in?", sl: "Kje je check-in?", cat: "airport" },
    { id: 22, es: "¿Dónde está la puerta 5?", sl: "Kje je izhod 5?", cat: "airport" },
    { id: 23, es: "Tengo un vuelo a Madrid", sl: "Imam let v Madrid", cat: "airport" },
    { id: 24, es: "¿Dónde recojo mi equipaje?", sl: "Kje dvignem prtljago?", cat: "airport" },
    { id: 25, es: "He perdido mi equipaje", sl: "Izgubil/a sem prtljago", cat: "airport" },
    { id: 26, es: "¿Es esta la puerta correcta?", sl: "Je to pravi izhod?", cat: "airport" },
    { id: 27, es: "¿Cuándo empieza el embarque?", sl: "Kdaj začne vkrcavanje?", cat: "airport" },
    { id: 28, es: "¿Dónde está la aduana?", sl: "Kje je carina?", cat: "airport" },
    { id: 29, es: "No tengo nada que declarar", sl: "Nimam ničesar za prijaviti", cat: "airport" },
    { id: 30, es: "¿Puedo tener un asiento de ventana?", sl: "Lahko dobim sedež ob oknu?", cat: "airport" },
    { id: 31, es: "¿El vuelo está a tiempo?", sl: "Je let punktualen?", cat: "airport" },
    { id: 32, es: "¿Dónde está la sala de embarque?", sl: "Kje je čakalnica?", cat: "airport" },
    
    // Restaurant - Restavracija
    { id: 33, es: "Una mesa para dos, por favor", sl: "Mizo za dve osebi, prosim", cat: "restaurant" },
    { id: 34, es: "¿Puedo ver el menú?", sl: "Lahko vidim meni?", cat: "restaurant" },
    { id: 35, es: "¿Qué recomienda?", sl: "Kaj priporočate?", cat: "restaurant" },
    { id: 36, es: "Voy a tomar esto", sl: "To bom vzel/vzela", cat: "restaurant" },
    { id: 37, es: "La cuenta, por favor", sl: "Račun, prosim", cat: "restaurant" },
    { id: 38, es: "La comida estaba deliciosa", sl: "Hrana je bila odlična", cat: "restaurant" },
    { id: 39, es: "Soy vegetariano/a", sl: "Sem vegetarijanec/ka", cat: "restaurant" },
    { id: 40, es: "¿Tienen opciones veganas?", sl: "Imate veganske opcije?", cat: "restaurant" },
    { id: 41, es: "Tengo alergia alimentaria", sl: "Imam alergijo na hrano", cat: "restaurant" },
    { id: 42, es: "¿Puedo tener agua, por favor?", sl: "Lahko dobim vodo?", cat: "restaurant" },
    { id: 43, es: "¿El servicio está incluido?", sl: "Je servis vključen?", cat: "restaurant" },
    { id: 44, es: "¿Aceptan tarjetas de crédito?", sl: "Sprejemate kartice?", cat: "restaurant" },
    { id: 45, es: "Esto no es lo que pedí", sl: "To ni kar sem naročil/a", cat: "restaurant" },
    { id: 46, es: "¿Puedo tener más pan?", sl: "Lahko dobim še kruha?", cat: "restaurant" },
    { id: 47, es: "¡Salud!", sl: "Na zdravje!", cat: "restaurant" },
    
    // Shopping - Nakupovanje
    { id: 48, es: "¿Cuánto cuesta esto?", sl: "Koliko stane to?", cat: "shopping" },
    { id: 49, es: "¿Puedo probármelo?", sl: "Lahko pomerim?", cat: "shopping" },
    { id: 50, es: "¿Tiene esto en otra talla?", sl: "Imate v drugi velikosti?", cat: "shopping" },
    { id: 51, es: "¿Tiene esto en otro color?", sl: "Imate v drugi barvi?", cat: "shopping" },
    { id: 52, es: "Solo estoy mirando", sl: "Samo gledam", cat: "shopping" },
    { id: 53, es: "¿Puede hacer un descuento?", sl: "Lahko dobim popust?", cat: "shopping" },
    { id: 54, es: "Me lo llevo", sl: "Vzamem", cat: "shopping" },
    { id: 55, es: "¿Aceptan tarjetas?", sl: "Sprejemate kartice?", cat: "shopping" },
    { id: 56, es: "¿Puedo tener un recibo?", sl: "Lahko dobim račun?", cat: "shopping" },
    { id: 57, es: "¿Está en oferta?", sl: "Je to na razprodaji?", cat: "shopping" },
    { id: 58, es: "¿Dónde está el probador?", sl: "Kje je garderoba?", cat: "shopping" },
    { id: 59, es: "¿Puedo devolverlo?", sl: "Lahko to vrnem?", cat: "shopping" },
    { id: 60, es: "Es muy caro", sl: "To je predrago", cat: "shopping" },
    { id: 61, es: "¿Tiene una bolsa?", sl: "Imate vrečko?", cat: "shopping" },
    
    // Hotel - Hotel
    { id: 62, es: "Tengo una reserva", sl: "Imam rezervacijo", cat: "hotel" },
    { id: 63, es: "¿Puedo hacer el check-in?", sl: "Se lahko prijavim?", cat: "hotel" },
    { id: 64, es: "¿A qué hora es el check-out?", sl: "Kdaj je check-out?", cat: "hotel" },
    { id: 65, es: "¿Puede despertarme?", sl: "Lahko dobim budilko?", cat: "hotel" },
    { id: 66, es: "La habitación está muy fría", sl: "Soba je premrzla", cat: "hotel" },
    { id: 67, es: "La habitación está muy caliente", sl: "Soba je prevroča", cat: "hotel" },
    { id: 68, es: "¿Puedo tener toallas extras?", sl: "Lahko dobim dodatne brisače?", cat: "hotel" },
    { id: 69, es: "El WiFi no funciona", sl: "WiFi ne deluje", cat: "hotel" },
    { id: 70, es: "¿Dónde se sirve el desayuno?", sl: "Kje se streže zajtrk?", cat: "hotel" },
    { id: 71, es: "¿Puedo extender mi estancia?", sl: "Lahko podaljšam bivanje?", cat: "hotel" },
    { id: 72, es: "¿El desayuno está incluido?", sl: "Je zajtrk vključen?", cat: "hotel" },
    { id: 73, es: "¿Puedo tener una habitación con vista?", sl: "Lahko dobim sobo s pogledom?", cat: "hotel" },
    { id: 74, es: "Mi llave no funciona", sl: "Ključ ne deluje", cat: "hotel" },
    { id: 75, es: "¿Puede llamar un taxi?", sl: "Lahko pokličete taksi?", cat: "hotel" },
    
    // Transport - Transport
    { id: 76, es: "¿Dónde está la parada de autobús?", sl: "Kje je avtobusna postaja?", cat: "transport" },
    { id: 77, es: "¿Cuánto cuesta un billete?", sl: "Koliko stane vozovnica?", cat: "transport" },
    { id: 78, es: "¿Este autobús va al centro?", sl: "Ta avtobus vozi v center?", cat: "transport" },
    { id: 79, es: "¿Dónde está la estación de tren?", sl: "Kje je železniška postaja?", cat: "transport" },
    { id: 80, es: "Necesito un taxi", sl: "Potrebujem taksi", cat: "transport" },
    { id: 81, es: "Lléveme a esta dirección", sl: "Peljite me na ta naslov", cat: "transport" },
    { id: 82, es: "¿Cuánto tiempo tarda?", sl: "Koliko časa traja?", cat: "transport" },
    { id: 83, es: "¿Puedo tener un billete a Barcelona?", sl: "Vozovnico za Barcelono?", cat: "transport" },
    { id: 84, es: "¿Es este el andén correcto?", sl: "Je to pravi peron?", cat: "transport" },
    { id: 85, es: "Pare aquí, por favor", sl: "Ustavite tukaj", cat: "transport" },
    { id: 86, es: "¿Dónde puedo alquilar un coche?", sl: "Kje lahko najamem avto?", cat: "transport" },
    { id: 87, es: "¿Cuánto por día?", sl: "Koliko na dan?", cat: "transport" },
    
    // Emergency - Nujno
    { id: 88, es: "¡Ayuda!", sl: "Pomoč!", cat: "emergency" },
    { id: 89, es: "¡Llame a la policía!", sl: "Pokličite policijo!", cat: "emergency" },
    { id: 90, es: "Necesito un médico", sl: "Potrebujem zdravnika", cat: "emergency" },
    { id: 91, es: "¿Dónde está el hospital?", sl: "Kje je bolnišnica?", cat: "emergency" },
    { id: 92, es: "Me han robado", sl: "Oropali so me", cat: "emergency" },
    { id: 93, es: "He perdido mi pasaporte", sl: "Izgubil/a sem potni list", cat: "emergency" },
    { id: 94, es: "No me siento bien", sl: "Ne počutim se dobro", cat: "emergency" },
    { id: 95, es: "Llame una ambulancia", sl: "Pokličite rešilca", cat: "emergency" },
    { id: 96, es: "Necesito ayuda", sl: "Potrebujem pomoč", cat: "emergency" },
    { id: 97, es: "¿Dónde está la farmacia?", sl: "Kje je lekarna?", cat: "emergency" },
    { id: 98, es: "Soy alérgico a...", sl: "Alergičen/na sem na...", cat: "emergency" },
    { id: 99, es: "¡Fuego!", sl: "Požar!", cat: "emergency" },
    { id: 100, es: "Que tengas un buen día", sl: "Lep dan", cat: "basic" }
];
